"""Router training examples — 100 query classification examples."""
from __future__ import annotations
from typing import Any, Dict, List
from examples._helpers import router_msg


def generate_router_examples() -> List[Dict[str, Any]]:
    examples = []
    for q, a in _DATA:
        examples.append(router_msg(q, a))
    return examples


def _route(darshana: str, guna: str, reasoning: str) -> str:
    return f"darshana: {darshana}\nguna: {guna}\nreasoning: {reasoning}"


_DATA: List[tuple] = [
    # Nyaya (logic, proof, validation) — 15 examples
    ("Is it true that remote workers are less productive than office workers?",
     _route("nyaya", "sattva", "This is a truth claim requiring logical validation — testing the claim 'remote = less productive' against evidence and identifying logical fallacies in the argument.")),
    ("Prove that our caching strategy reduces latency.",
     _route("nyaya", "sattva", "Explicit proof request. Requires constructing a formal argument with evidence, testing premises, and identifying potential fallacies.")),
    ("Our CEO says AI will replace all developers within 5 years. Is this reasoning sound?",
     _route("nyaya", "sattva", "A specific claim requiring logical stress-testing — evaluating premises, checking for fallacies, and assessing conclusion validity.")),
    ("Does correlation between ice cream sales and drowning deaths mean one causes the other?",
     _route("nyaya", "sattva", "Classic logical fallacy detection — correlation vs causation. Requires formal syllogistic analysis.")),
    ("Is it valid to say that since our competitor failed with this strategy, we will too?",
     _route("nyaya", "sattva", "Logical validity question — testing an argument from analogy for potential fallacies.")),
    ("My professor argues that consciousness is just computation. Evaluate this claim.",
     _route("nyaya", "sattva", "A philosophical truth claim requiring formal logical analysis and premise testing.")),
    ("Is the argument 'we should use Kubernetes because Google uses it' logically sound?",
     _route("nyaya", "sattva", "Appeal to authority fallacy detection. Requires formal logical evaluation.")),
    ("Can we prove that our new algorithm is strictly faster than the old one?",
     _route("nyaya", "sattva", "Formal proof request with precise truth conditions.")),
    ("A study claims meditation reduces anxiety. The sample was 20 people. Is this valid?",
     _route("nyaya", "sattva", "Evidence evaluation — testing the strength of a scientific claim and its premises.")),
    ("Is it true that startups should always move fast and break things?",
     _route("nyaya", "sattva", "Universal claim requiring logical stress-testing — checking if the hetu is too broad.")),
    ("Our board says we must cut costs OR raise revenue. Is this a false dichotomy?",
     _route("nyaya", "sattva", "Explicit logical structure question — evaluating whether a disjunction is genuine or fallacious.")),
    ("Evaluate whether this argument is circular: 'The Bible is true because God wrote it, and we know God exists because the Bible says so.'",
     _route("nyaya", "sattva", "Explicit fallacy identification — circular reasoning / begging the question.")),
    ("Does the fact that vaccines have side effects prove they are dangerous?",
     _route("nyaya", "sattva", "Logical validity of an inference from 'has side effects' to 'is dangerous' — requires premise testing.")),
    ("Is it logically valid to conclude that since every part of the car is light, the whole car is light?",
     _route("nyaya", "sattva", "Composition fallacy detection — a formal logic problem.")),
    ("Our tech lead says TypeScript prevents all runtime errors. Evaluate this claim.",
     _route("nyaya", "sattva", "Truth claim evaluation — testing an absolute claim against reality.")),

    # Samkhya (enumeration, decomposition) — 15 examples
    ("What are all the things that could go wrong with our product launch?",
     _route("samkhya", "sattva", "Exhaustive enumeration request — list all failure modes with causal relationships.")),
    ("Break down all the costs involved in running our SaaS platform.",
     _route("samkhya", "sattva", "Component enumeration — requires systematic counting of all cost categories.")),
    ("What are all the stakeholders affected by this policy change?",
     _route("samkhya", "sattva", "Stakeholder enumeration — exhaustive listing with interests and relationships.")),
    ("List every step in our deployment pipeline.",
     _route("samkhya", "tamas", "Sequential component listing — process enumeration in causal order.")),
    ("What are the layers of our technology stack?",
     _route("samkhya", "tamas", "Layer enumeration — architectural decomposition from abstract to concrete.")),
    ("Map out all the factors affecting employee retention.",
     _route("samkhya", "sattva", "Factor enumeration with causal relationships — complex system mapping.")),
    ("What goes into a hiring decision?",
     _route("samkhya", "sattva", "Decision component enumeration — listing all inputs to a complex decision.")),
    ("Enumerate all the ways our data could be compromised.",
     _route("samkhya", "sattva", "Threat enumeration — exhaustive listing of attack vectors and vulnerabilities.")),
    ("What are all the components of a good user onboarding experience?",
     _route("samkhya", "sattva", "Experience component enumeration — listing all touchpoints and requirements.")),
    ("Break down the human immune system's response to infection.",
     _route("samkhya", "sattva", "Biological system enumeration — complex causal chain with branches.")),
    ("What are all the types of technical debt in our codebase?",
     _route("samkhya", "sattva", "Classification enumeration — categorizing and counting instances.")),
    ("Map all the dependencies in our microservices architecture.",
     _route("samkhya", "sattva", "Dependency enumeration with directed relationships.")),
    ("What components make up a complete CI/CD pipeline?",
     _route("samkhya", "tamas", "Pipeline component enumeration in sequential order.")),
    ("List all the factors that determine a company's culture.",
     _route("samkhya", "rajas", "Broad enumeration requiring creative identification of non-obvious factors.")),
    ("What are all the metrics we should track for our marketplace?",
     _route("samkhya", "sattva", "Metric enumeration — comprehensive measurement framework.")),

    # Yoga (attention, filtering, focus) — 15 examples
    ("We have 50 features on our roadmap. How do we decide which 3 to build?",
     _route("yoga", "sattva", "Signal-noise filtering — requires scoring factors, applying cutoff, and finding the single focus point.")),
    ("I'm overwhelmed with information about this problem. What actually matters?",
     _route("yoga", "sattva", "Explicit noise-reduction request — needs systematic filtering to find the dharana point.")),
    ("What should I focus on in the next 90 days to grow my career?",
     _route("yoga", "sattva", "Priority filtering — requires inventorying all options and ruthlessly discarding distractions.")),
    ("Our dashboard has 200 metrics. Which ones should executives see?",
     _route("yoga", "sattva", "Signal filtering from noise — reducing a large input set to the essential few.")),
    ("What's the one thing that would make the biggest difference for our product?",
     _route("yoga", "sattva", "Explicit dharana point request — finding the single highest-leverage intervention.")),
    ("How do I decide which side project to finish?",
     _route("yoga", "sattva", "Attention allocation problem — requires filtering options by actual priority.")),
    ("There are too many opinions about this architecture. How do I cut through the noise?",
     _route("yoga", "sattva", "Signal-noise separation in a high-noise environment.")),
    ("What should a startup with 6 months runway focus on?",
     _route("yoga", "sattva", "Extreme priority filtering under constraint — find the one thing that matters.")),
    ("Which of these 10 job offers should I take?",
     _route("yoga", "sattva", "Multi-option filtering — score factors, discard noise, find dharana point.")),
    ("Our team is pulled in too many directions. How do we focus?",
     _route("yoga", "sattva", "Organizational attention management — systematic focus identification.")),
    ("What should I study for this exam given limited time?",
     _route("yoga", "sattva", "Study priority filtering — score topics by likelihood and impact, apply cutoff.")),
    ("How do I prioritize bugs, features, and tech debt?",
     _route("yoga", "sattva", "Three-category priority filtering — needs unified scoring framework.")),
    ("Which customer segment should we target first?",
     _route("yoga", "sattva", "Segment filtering — score segments, discard noise factors, find focus.")),
    ("Should we invest in marketing or product? Our team argues both.",
     _route("yoga", "sattva", "Binary choice with noise from both sides — find the actual deciding factor.")),
    ("What matters most when evaluating a new technology?",
     _route("yoga", "sattva", "Technology evaluation filtering — separate signal from hype.")),

    # Vedanta (contradiction resolution) — 15 examples
    ("Our engineering team wants velocity but our QA team wants thoroughness. How do we resolve this?",
     _route("vedanta", "sattva", "Explicit contradiction between two positions — requires adhyaropa-apavada to find what is real beneath the opposition.")),
    ("Is AI creative or just pattern matching? People disagree strongly.",
     _route("vedanta", "rajas", "Philosophical contradiction — two seemingly incompatible claims about AI. Needs Vedanta's superimposition-negation method.")),
    ("Remote vs office — the debate seems unresolvable. What are we missing?",
     _route("vedanta", "sattva", "Persistent contradiction — requires finding the hidden assumption both sides share.")),
    ("We need to move fast but also be careful with user data. These seem incompatible.",
     _route("vedanta", "sattva", "Apparent contradiction between speed and care — needs reframing.")),
    ("Is it better to be a specialist or generalist?",
     _route("vedanta", "rajas", "Classic either/or that Vedanta resolves through reframing.")),
    ("Capitalism drives innovation but also creates inequality. Can these be reconciled?",
     _route("vedanta", "rajas", "Deep systemic contradiction — requires finding what is real beneath both claims.")),
    ("Our CEO and CTO disagree on build vs buy. Neither will budge.",
     _route("vedanta", "sattva", "Organizational contradiction requiring the Mahavakya reframing.")),
    ("Free will vs determinism — is there a resolution?",
     _route("vedanta", "rajas", "Philosophical contradiction — classical Vedanta territory.")),
    ("Should education focus on skills or knowledge? My team is split.",
     _route("vedanta", "sattva", "Binary opposition requiring resolution through finding what both sides share.")),
    ("The trolley problem — is there actually a right answer?",
     _route("vedanta", "rajas", "Moral contradiction — requires finding what survives negation of both positions.")),
    ("Our customers want simplicity but our power users demand features.",
     _route("vedanta", "sattva", "Product design contradiction — opposing user needs.")),
    ("Is consciousness an emergent property or fundamental?",
     _route("vedanta", "rajas", "Metaphysical contradiction — Vedanta's core domain.")),
    ("Open source vs proprietary — which produces better software?",
     _route("vedanta", "sattva", "Development philosophy contradiction — needs reframing.")),
    ("We want to be data-driven but also trust our intuition. How?",
     _route("vedanta", "sattva", "Epistemological contradiction — data vs intuition.")),
    ("Agile says respond to change; our enterprise clients want stability.",
     _route("vedanta", "sattva", "Process contradiction requiring higher-order resolution.")),

    # Mimamsa (text → action) — 15 examples
    ("Here's our project requirements doc. Extract the specific action items.",
     _route("mimamsa", "sattva", "Explicit text-to-action request — parse sentences into vidhi/arthavada/mantra/nishedha.")),
    ("What does this contract clause actually require us to do?",
     _route("mimamsa", "sattva", "Legal text interpretation — extract executable obligations from contractual language.")),
    ("Parse this user story into implementable tasks.",
     _route("mimamsa", "sattva", "Text decomposition into agent-action-object specifications.")),
    ("What are the actual requirements hidden in this meeting transcript?",
     _route("mimamsa", "sattva", "Extract commands from natural language conversation.")),
    ("Convert this regulatory guidance into a compliance checklist.",
     _route("mimamsa", "sattva", "Regulatory text to executable specifications.")),
    ("What does this SLA actually commit us to?",
     _route("mimamsa", "sattva", "Contract interpretation — identify specific obligations and prohibitions.")),
    ("Parse this incident report into action items and preventive measures.",
     _route("mimamsa", "sattva", "Post-mortem text to structured remediation plan.")),
    ("What does this API documentation tell us to do and not do?",
     _route("mimamsa", "sattva", "Technical documentation interpretation — extract dos and don'ts.")),
    ("Translate this product vision statement into quarterly objectives.",
     _route("mimamsa", "sattva", "Vision text to executable time-bound objectives.")),
    ("What does this privacy policy actually allow and prohibit?",
     _route("mimamsa", "sattva", "Policy text to permissions/restrictions classification.")),
    ("Convert this design brief into engineering tickets.",
     _route("mimamsa", "sattva", "Creative brief to implementation specifications.")),
    ("What are the prohibitions in this code of conduct?",
     _route("mimamsa", "sattva", "Extract nishedha (prohibitions) from organizational policy.")),
    ("Parse this email chain and tell me what I need to do.",
     _route("mimamsa", "tamas", "Email to action items — practical text interpretation.")),
    ("What does this academic paper's conclusion actually tell practitioners to do?",
     _route("mimamsa", "sattva", "Research text to practical recommendations.")),
    ("Extract the key decisions and action items from this board meeting minutes.",
     _route("mimamsa", "sattva", "Meeting text to structured decisions and actions.")),

    # Vaisheshika (atomic decomposition) — 15 examples
    ("What are the irreducible components of a microservice?",
     _route("vaisheshika", "sattva", "Explicit atomic decomposition request — decompose until you hit bedrock components.")),
    ("Break this system design down to its smallest building blocks.",
     _route("vaisheshika", "sattva", "Recursive decomposition to atomic components with classification.")),
    ("What is a database index at its most fundamental level?",
     _route("vaisheshika", "sattva", "Seeking atomic understanding — decompose the concept to irreducible elements.")),
    ("What are the type primitives of our domain model?",
     _route("vaisheshika", "sattva", "Type system decomposition — ontological classification.")),
    ("Decompose 'user engagement' into measurable atomic units.",
     _route("vaisheshika", "sattva", "Abstract concept decomposition into concrete, measurable atoms.")),
    ("What are the fundamental building blocks of a programming language?",
     _route("vaisheshika", "sattva", "Language design decomposition to irreducible elements.")),
    ("What are the atomic operations in a distributed system?",
     _route("vaisheshika", "sattva", "System decomposition to smallest indivisible operations.")),
    ("Break down 'security' into its irreducible components.",
     _route("vaisheshika", "sattva", "Security concept decomposition — find the atoms.")),
    ("What are the fundamental types in our event-driven architecture?",
     _route("vaisheshika", "sattva", "Type classification — ontological decomposition.")),
    ("Decompose a 'customer journey' to atomic touchpoints.",
     _route("vaisheshika", "sattva", "Experience decomposition to irreducible interaction units.")),
    ("What makes a function 'pure' at the most fundamental level?",
     _route("vaisheshika", "sattva", "Concept decomposition to defining properties.")),
    ("Break down our data model to its most basic entities and relationships.",
     _route("vaisheshika", "sattva", "Data model decomposition with entity-relationship classification.")),
    ("What are the atomic units of a neural network?",
     _route("vaisheshika", "sattva", "ML architecture decomposition to irreducible components.")),
    ("Decompose 'code review quality' into fundamental measurable components.",
     _route("vaisheshika", "sattva", "Abstract quality decomposition into measurable atoms.")),
    ("What are the essential vs accidental properties of our API?",
     _route("vaisheshika", "sattva", "Samavaya vs samyoga classification — distinguishing essential from accidental properties.")),

    # Multi-darshana routing — 10 examples
    ("Should we rewrite our system in Rust? The team is split and we need to analyze this thoroughly.",
     _route("nyaya, vedanta", "sattva", "Multi-darshana: Nyaya for evaluating the logical claims about Rust's benefits, Vedanta for resolving the team's contradiction. The claim 'rewrite in Rust' needs logical stress-testing, and the team split needs reframing.")),
    ("We need to completely redesign our onboarding flow. Where do we start?",
     _route("samkhya, yoga", "sattva", "Multi-darshana: Samkhya to enumerate all onboarding components, then Yoga to filter and find the single highest-leverage improvement.")),
    ("Parse this legal contract and tell me if the terms are actually fair.",
     _route("mimamsa, nyaya", "sattva", "Multi-darshana: Mimamsa to extract the specific obligations and prohibitions from the text, Nyaya to evaluate whether the stated justifications are logically sound.")),
    ("What is a Kubernetes pod at its most fundamental level, and what are all its components?",
     _route("vaisheshika, samkhya", "sattva", "Multi-darshana: Vaisheshika for atomic decomposition to irreducible units, Samkhya for exhaustive enumeration with causal chains.")),
    ("Our team can't agree on monolith vs microservices, and we need to actually build something. Help.",
     _route("vedanta, yoga", "sattva", "Multi-darshana: Vedanta to resolve the contradiction (what is real beneath both positions), Yoga to find the single focus point that breaks the deadlock.")),
    ("Analyze this research paper's methodology and conclusions — is it valid, what does it actually say to do, and what should I focus on?",
     _route("nyaya, mimamsa, yoga", "sattva", "Multi-darshana: Nyaya for logical validation of conclusions, Mimamsa for extracting actionable recommendations, Yoga for filtering to the single most important finding.")),
    ("Help me understand all the components of our billing system, find the weak points, and prioritize fixes.",
     _route("samkhya, vaisheshika, yoga", "sattva", "Multi-darshana: Samkhya for exhaustive enumeration, Vaisheshika for atomic decomposition of weak components, Yoga for prioritizing the highest-leverage fix.")),
    ("Two team members have completely different interpretations of this requirements document.",
     _route("mimamsa, vedanta", "sattva", "Multi-darshana: Mimamsa for rigorous textual interpretation to determine what the document actually says, Vedanta for resolving the contradiction between interpretations.")),
    ("We need to evaluate whether our startup's thesis is logically sound and enumerate all the things that need to be true for it to work.",
     _route("nyaya, samkhya", "sattva", "Multi-darshana: Nyaya for logical validation of the thesis, Samkhya for exhaustive enumeration of assumptions and dependencies.")),
    ("I need to deeply understand what a 'transaction' is at the database level and whether our transaction strategy is logically sound.",
     _route("vaisheshika, nyaya", "sattva", "Multi-darshana: Vaisheshika for atomic decomposition of a transaction, Nyaya for logical evaluation of our transaction strategy.")),
]
